# Generated by Django 4.0.3 on 2022-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.IntegerField()),
                ('documento', models.CharField(max_length=255)),
                ('hobbie', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('tipo_documento', 'documento')},
            },
        ),
    ]
